export default {
    addUser: 'INSERT INTO user(name, type, passcode, passrd) VALUES(?,?,?,?)',
    queryUserWithLimit: 'SELECT * FROM user WHERE type <= ? LIMIT ?,?',
    countQueryUserWithLimit: 'SELECT COUNT(*) FROM user WHERE type <= ?',
    getUserById: 'SELECT * FROM user WHERE id=?',
    searchUserWithLimited: 'SELECT * FROM user WHERE (type <= ? and (POSITION(? IN name) OR POSITION(? IN id))) LIMIT ?,?',
    countSearchUserWithLimited: 'SELECT COUNT(*) FROM user WHERE (type <= ? and (POSITION(? IN name) OR POSITION(? IN id)))',
    resetPassword: 'UPDATE user SET passcode=?, passrd=? WHERE id=?',
    deleteUser: 'DELETE FROM user WHERE id=?',
    resetUserType: 'UPDATE user SET type=? WHERE id=?',
    resetUserName: 'UPDATE user SET name=? WHERE id=?',
    //total: 'SELECT FOUND_ROWS()',
    addPhoto: 'INSERT INTO photo(uploader_id, type, date) VALUES(?, 0, now())',
    updatePhoto: 'UPDATE photo SET type=1 WHERE id=?',
    publishPhoto: 'UPDATE photo SET type=2, name=? WHERE id=?',
    queryUnPublishedPhotoWithLimit: 'SELECT photo.id as id, photo.type as type, photo.name as name, photo.uploader_id as uploader_id, user.type as uploader_type, user.name as uploader_name FROM photo LEFT OUTER JOIN user ON user.id = photo.uploader_id WHERE user.type <= ? AND (photo.type = 0 OR photo.type = 1) LIMIT ?,?',
    countQueryUnPublishedPhotoWithLimit: 'SELECT COUNT(*) FROM photo LEFT OUTER JOIN user ON user.id = photo.uploader_id WHERE user.type <= ? AND (photo.type = 0 OR photo.type = 1)',
};